package g.dbz.cardgame.enumerator;

public enum Level {
//LOW LEVEL
	PLANET1, PLANET2, PLANET3, PLANET4, PLANET5, PLANET6,
//
//MID LEVEL
	SPACE1, SPACE2, SPACE3, SPACE4, SPACE5, SPACE6,
//
//HIGH LEVEL
	LEGEND1, LEGEND2, LEGEND3, LEGEND4, LEGEND5, LEGEND6,
//
//GOD LEVEL
	GOD1, GOD2, GOD3, GOD4, GOD5, GOD6, GOD7;
//
}
